name: Nightly build

on:
  workflow_dispatch:
    inputs:
      no_release:
        description: "Do not generate a github release for this build"
        type: boolean
        required: true
        default: true
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Z threads=4 -Z share-generics=y

jobs:
  check_date:
    name: Check latest commit is recent enough
    runs-on: ubuntu-slim
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5
      - name: Print latest commit
        run: echo ${{ github.sha }}
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list --max-count=1 --after="24 hours" ${{ github.sha }}) && echo "should_run=false" >> "$GITHUB_OUTPUT"

  generate_name:
    name: Generate build artifact name
    runs-on: ubuntu-slim
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    outputs:
      name_linux: ${{ steps.generate_name.outputs.name_linux }}
      name_windows: ${{ steps.generate_name.outputs.name_windows }}
      name_macos: ${{ steps.generate_name.outputs.name_macos }}
      date: ${{ steps.generate_date.outputs.date }}
      tag: ${{ steps.generate_tag.outputs.tag }}
    steps:
      - id: generate_name
        run: |
          echo "name_linux=lazuli-linux-$(date -u +%y%m%d)" >> "$GITHUB_OUTPUT"
          echo "name_windows=lazuli-windows-$(date -u +%y%m%d).exe" >> "$GITHUB_OUTPUT"
          echo "name_macos=lazuli-macos-$(date -u +%y%m%d)" >> "$GITHUB_OUTPUT"
      - id: generate_date
        run: echo "date=$(date -u +%Y/%m/%d )" >> "$GITHUB_OUTPUT"
      - id: generate_tag
        run: echo "tag=nightly-$(date -u +%y%m%d)" >> "$GITHUB_OUTPUT"

  build_linux:
    name: Build nightly (linux)
    runs-on: ubuntu-latest
    needs: [check_date, generate_name]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Update apt
        run: sudo apt-get update
      - name: Install audio deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libasound2-dev libudev-dev
      - name: Install rust toolchain
        run: rustup toolchain install
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.7
        with:
          cache-on-failure: true
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build ipl-hle
        run: just ipl-hle build
      - name: Build lazuli
        run: cargo build --profile release-dist
      - name: Compress debug sections
        run: objcopy --compress-debug-sections=zstd ./target/release-dist/app ./target/release-dist/${{ needs.generate_name.outputs.name_linux }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.generate_name.outputs.name_linux }}
          path: ./target/release-dist/${{ needs.generate_name.outputs.name_linux }}

  build_windows:
    name: Build nightly (windows)
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    needs: [check_date, generate_name]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install rust toolchain
        run: rustup toolchain install
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.7
        with:
          cache-on-failure: true
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build ipl-hle
        run: just ipl-hle build
      - name: Build lazuli
        run: cargo build --profile release-dist
      - name: Rename executable
        run: mv ./target/release-dist/app.exe ./target/release-dist/${{ needs.generate_name.outputs.name_windows }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.generate_name.outputs.name_windows }}
          path: ./target/release-dist/${{ needs.generate_name.outputs.name_windows }}

  build_macos:
    name: Build nightly (macos-aarch64)
    runs-on: macos-latest
    needs: [check_date, generate_name]
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install rust toolchain
        run: rustup toolchain install
      - name: Rust cache
        uses: Swatinem/rust-cache@v2.7.7
        with:
          cache-on-failure: true
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Build ipl-hle
        run: just ipl-hle build
      - name: Build lazuli
        run: cargo build --profile release-dist
      - name: Sign Binary with JIT Entitlements (macOS Specific)
        run: codesign -s - --entitlements resources/macos/entitlements.plist --force target/release-dist/app
      - name: Strip debug symbols
        run: strip ./target/release-dist/app
      - name: Rename executable
        run: mv ./target/release-dist/app ./target/release-dist/${{ needs.generate_name.outputs.name_macos }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.generate_name.outputs.name_macos }}
          path: ./target/release-dist/${{ needs.generate_name.outputs.name_macos }}

  release:
    name: Create nightly release
    runs-on: ubuntu-slim
    needs: [check_date, generate_name, build_linux, build_windows, build_macos]
    if: ${{ needs.check_date.outputs.should_run != 'false' && !inputs.no_release }}
    permissions:
      contents: write
    steps:
      - name: Download linux artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.generate_name.outputs.name_linux }}
          path: build
      - name: Download windows artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.generate_name.outputs.name_windows }}
          path: build
      - name: Download macos artifactss
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.generate_name.outputs.name_macos }}
          path: build
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Lazuli Nightly (${{ needs.generate_name.outputs.date }})
          body: Nightly release ${{ needs.generate_name.outputs.date }}
          files: build/*
          tag_name: ${{ needs.generate_name.outputs.tag }}
          make_latest: true
          prerelease: false
